apiVersion: batch/v1
kind: Job
metadata:
  name: nccl-allreduce-gpu
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app: nccl-test
    spec:
      restartPolicy: Never
      containers:
        - name: nccl-allreduce
          image: nvcr.io/nvidia/hpc-benchmarks:25.04
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              TS=$(date +%Y%m%dT%H%M%S)
              # Note: '-np 8' is overridden at runtime by K8sNcclWorkload
              mpirun --allow-run-as-root -np 8 \
                     --bind-to none --map-by slot \
                     -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH \
                     all_reduce_perf_mpi -b 8 -e 2G -f 2 -g 1 \
                     2>&1 | tee /results/nccl-allreduce_${TS}.log
          volumeMounts:
            - name: results
              mountPath: /results
          resources:
            limits:
              nvidia.com/gpu: 8 # overridden at runtime by K8sNcclWorkload
          securityContext:
            #  runAsNonRoot: true
            allowPrivilegeEscalation: false
      nodeSelector:
        nvidia.com/gpu.present: "true"
      runtimeClassName: nvidia
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
        - name: results
          hostPath:
            path: /data/nvstgt/results
            type: DirectoryOrCreate
